services:
  - type: web
    name: automacao-mega-paine
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: USER_EMAIL
        sync: false
      - key: USER_PASSWORD
        sync: false

